# Generated by Django 4.0.2 on 2022-09-07 15:26

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=200, populate_from='title'),
        ),
    ]
