# Generated by Django 4.0.2 on 2022-09-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodies', '0005_remove_recipe_image_alter_recipe_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
