# Generated by Django 4.0.2 on 2022-09-12 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userextend', '0003_remove_userextend_gender'),
        ('foodies', '0006_recipe_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodies.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userextend.userextend')),
            ],
        ),
    ]
