# Generated by Django 4.0.2 on 2022-09-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodies', '0007_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
