# Generated by Django 4.0.2 on 2022-09-02 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userextend', '0002_remove_userextend_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextend',
            name='gender',
        ),
    ]
